import { AppWrapper } from '@/components/AppWrapper.component'
import './globals.css'
import type { Metadata } from 'next'
import '@shopify/polaris/build/esm/styles.css'

export const metadata: Metadata = {
  title: 'Create Shopify App',
  description: 'Generated by create shopify app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AppWrapper>{children}</AppWrapper>
      </body>
    </html>
  )
}
